version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - blue
      - green
    networks:
      - webnet

  blue:
    build: .
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "https://astraiosissda.shop/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_KEY=${SECRET_KEY}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY}
      - S3_ACCESS_KEY2=${S3_ACCESS_KEY2}
      - S3_SECRET_ACCESS_KEY2=${S3_SECRET_ACCESS_KEY2}
      - KAKAO_REDIRECT_URI=${KAKAO_REDIRECT_URI}
      - KAKAO_CLIENT_ID=${KAKAO_CLIENT_ID}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - REACT_APP_GOOGLE_AUTH_REDIRECT_URI=${REACT_APP_GOOGLE_AUTH_REDIRECT_URI}
      - NAVER_CLIENT_ID=${NAVER_CLIENT_ID}
      - NAVER_CLIENT_SECRET=${NAVER_CLIENT_SECRET}
      - NAVER_REDIRECT_URI=${NAVER_REDIRECT_URI}
      - DB=${DB}
    networks:
      - webnet

  green:
    build: .
    restart : always
    healthcheck:
      test: ["CMD", "curl", "-f", "https://astraiosissda.shop/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_KEY=${SECRET_KEY}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY}
      - S3_ACCESS_KEY2=${S3_ACCESS_KEY2}
      - S3_SECRET_ACCESS_KEY2=${S3_SECRET_ACCESS_KEY2}
      - KAKAO_REDIRECT_URI=${KAKAO_REDIRECT_URI}
      - KAKAO_CLIENT_ID=${KAKAO_CLIENT_ID}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - REACT_APP_GOOGLE_AUTH_REDIRECT_URI=${REACT_APP_GOOGLE_AUTH_REDIRECT_URI}
      - NAVER_CLIENT_ID=${NAVER_CLIENT_ID}
      - NAVER_CLIENT_SECRET=${NAVER_CLIENT_SECRET}
      - NAVER_REDIRECT_URI=${NAVER_REDIRECT_URI}
      - DB=${DB}
    networks:
      - webnet

networks:
  webnet: