# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node


name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]


    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci

    - name: Check npm -v
      run: npm -v

    - name: create env file
      working-directory: ./
      run: |
        pwd
        touch .env
        echo DATABASE_URL=${{ secrets.DATABASE_URL }} >> .env
        echo SECRET_KEY=${{ secrets.SECRET_KEY }} >> .env
        echo REDIS_HOST=${{ secrets.REDIS_HOST }} >> .env
        echo REDIS_PORT=${{ secrets.REDIS_PORT }} >> .env
        echo REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }} >> .env
        echo KAKAO_REDIRECT_URI=${{ secrets.KAKAO_REDIRECT_URI }} >> .env
        echo KAKAO_CLIENT_ID=${{ secrets.KAKAO_CLIENT_ID }} >> .env
        echo GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }} >> .env
        echo GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }} >> .env
        echo REACT_APP_GOOGLE_AUTH_REDIRECT_URI=${{ secrets.REACT_APP_GOOGLE_AUTH_REDIRECT_URI }} >> .env
        echo S3_ACCESS_KEY=${{ secrets.S3_ACCESS_KEY }} >> .env
        echo S3_SECRET_ACCESS_KEY=${{ secrets.S3_SECRET_ACCESS_KEY }} >> .env
        echo NAVER_CLIENT_ID=${{ secrets.NAVER_CLIENT_ID }} >> .env
        echo NAVER_CLIENT_SECRET=${{ secrets.NAVER_CLIENT_SECRET }} >> .env
        echo NAVER_REDIRECT_URI=${{ secrets.NAVER_REDIRECT_URI }} >> .env
        echo S3_ACCESS_KEY2=${{ secrets.S3_ACCESS_KEY2 }} >> .env
        echo S3_SECRET_ACCESS_KEY2=${{ secrets.S3_SECRET_ACCESS_KEY2 }} >> .env
        echo MONGO_DB=${{ secrets.MONGO_DB }} >> .env
        echo MAILER_EMAIL=${{ secrets.MAILER_EMAIL }} >> .env
        echo MAILER_PASSWORD=${{ secrets.MAILER_PASSWORD }} >> .env
        cat .env
      
    - name: zip file
      run: zip -r CI.zip ./src/* ./prisma/* ./scripts/* ./appspec.yml ./package.json ./package-lock.json ./deploy.sh ./docker-compose.yml ./Dockerfile ./nginx.conf ./.env ./healthcheck_restart.sh

    - name: AWS configure credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_PRIVATE_ACCESS_KEY }}
        aws-region: ap-northeast-2

    - name: upload to S3
      run: aws s3 cp --region ap-northeast-2 ./CI.zip s3://myscope-bucket/deploy/


    - name: deploy with AWS codeDeploy
      run: aws deploy create-deployment
        --application-name my-codedeploy-app
        --deployment-config-name CodeDeployDefault.OneAtATime
        --deployment-group-name codedeploygroup
        --s3-location bucket=myscope-bucket,bundleType=zip,key=deploy/CI.zip
